go env -w GO111MODULE=on

go get -u -v bitbucket.org/bertimus9/systemstat              
go get -u -v git.zx2c4.com/wireguard-go                      
go get -u -v github.com/ChimeraCoder/gojson/gojson           
go get -u -v github.com/MontFerret/ferret                    
go get -u -v github.com/armon/go-socks5                      
go get -u -v github.com/bmizerany/pat
go get -u -v github.com/free/sql_exporter                    
go get -u -v github.com/go-chi/chi
go get -u -v github.com/go-playground/validator/v10
go get -u -v github.com/go-sql-driver/mysql
go get -u -v github.com/go-telegram-bot-api/telegram-bot-api 
go get -u -v github.com/golang/protobuf/proto                
go get -u -v github.com/golang/protobuf/protoc-gen-go        
go get -u -v github.com/golangcollege/sessions
go get -u -v github.com/google/goexpect                      
go get -u -v github.com/google/gopacket                      
go get -u -v github.com/google/mtail/cmd/mtail
go get -u -v github.com/gopherjs/gopherjs
go get -u -v github.com/gopherjs/vecty
go get -u -v github.com/gorilla/mux
go get -u -v github.com/gorilla/sessions
go get -u -v github.com/gorilla/websocket
go get -u -v github.com/intel-go/nff-go/flow                 
go get -u -v github.com/intel-go/nff-go/packet               
go get -u -v github.com/jlaffaye/ftp                         
go get -u -v github.com/jmoiron/sqlx
go get -u -v github.com/jstemmer/gotags                      
go get -u -v github.com/justinas/alice                       
go get -u -v github.com/justinas/nosurf
go get -u -v github.com/lib/pq                               
go get -u -v github.com/libp2p/go-libp2p                     
go get -u -v github.com/mattn/go-shellwords                  
go get -u -v github.com/mattn/go-sqlite3                     
go get -u -v github.com/messagebird/sachet
go get -u -v github.com/mitchellh/gox                        
go get -u -v github.com/prometheus/alertmanager/template
go get -u -v github.com/prometheus/client_golang/...
go get -u -v github.com/prometheus/common/model              
go get -u -v github.com/reconquest/orgalorg                  
go get -u -v github.com/shurcooL/goexec                      
go get -u -v github.com/spf13/cobra                          
go get -u -v github.com/spf13/pflag                          
go get -u -v github.com/spf13/viper                          
go get -u -v github.com/stretchr/testify/assert              
go get -u -v github.com/u-root/u-root
go get -u -v github.com/ziutek/telnet                        
go get -u -v go.uber.org/zap                                 
go get -u -v golang.org/x/crypto/...                             
go get -u -v golang.org/x/net                                
go get -u -v golang.org/x/oauth2                             
go get -u -v golang.org/x/sync                               
go get -u -v golang.org/x/sys                                
go get -u -v golang.org/x/text                               
go get -u -v golang.org/x/tools/cmd/godoc                    
go get -u -v google.golang.org/grpc                          
go get -u -v gopkg.in/tucnak/telebot.v2                      
